---
# Remove old conflicting packages first
- name: Remove old Docker and containerd versions
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
    purge: yes
    update_cache: yes

# Install dependencies
- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes

# Add Docker GPG key
- name: Add Docker GPG key
  ansible.builtin.apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

# Add Docker repository
- name: Add Docker apt repository
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present

# Install Docker CE + Compose plugin
- name: Install Docker CE
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
    update_cache: yes

# Configure insecure registry
- name: Configure Docker to allow insecure registry
  copy:
    dest: /etc/docker/daemon.json
    content: |
      {
        "insecure-registries": ["{{ nexus_registry }}"]
      }
  notify: Restart docker

# Log in to Nexus
- name: Log in to Nexus Docker registry
  community.docker.docker_login:
    registry_url: "http://{{ nexus_registry }}"
    username: "{{ nexus_username }}"
    password: "{{ nexus_password }}"

# Create app directory
- name: Create app directory
  file:
    path: /opt/vlink
    state: directory

# Deploy docker-compose file
- name: Deploy docker-compose file
  template:
    src: docker-compose.yml.j2
    dest: /opt/vlink/docker-compose.yml

# Pull and run
- name: Pull and run Docker container
  community.docker.docker_compose:
    project_src: /opt/vlink
    pull: yes
    restarted: yes
# Restart Docker service
- name: Restart docker
  service:
    name: docker
    state: restarted